{
 "title": "Ping Results",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Ping Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ping_latency{type=\"average\"}",
     "legendFormat": "Average"
    },
    {
     "expr": "ping_latency{type=\"minimum\"}",
     "legendFormat": "Minimum"
    },
    {
     "expr": "ping_latency{type=\"maximum\"}",
     "legendFormat": "Maximum"
    },
    {
     "expr": "ping_latency{type=\"mdev\"}",
     "legendFormat": "Standard Deviation"
    }
   ]
  },
  {
   "title": "% Packet Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "packet_loss", "legendFormat": "Packet Loss" }
   ]
  },
  {
   "title": "Max Packet Loss",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max_over_time(packet_loss[1d])", "legendFormat": "Max Packet Loss" }
   ]
  },
  {
   "title": "Amount of Packets Transmitted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "packets_transmitted", "legendFormat": "Max Packet Loss" }
   ]
  },
  {
   "title": "Packets Transmitted vs Received",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "packets_transmitted - packets_transmitted offset 1m",
     "legendFormat": "Packets Transmitted"
    },
    {
     "expr": "packets_received - packets_received offset 1m",
     "legendFormat": "Packets Received"
    }
   ]
  }
 ]
}